name: CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: Release
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release

    steps:
    - uses: actions/checkout@v2

    - name: Cache CMake files
      uses: actions/cache@v2
      with:
        path: |
          build
          ~/.cache/CMakeFiles
        key: ${{ runner.os }}-cmake-${{ matrix.cpp_compiler }}-${{ matrix.build_type }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y cmake g++ clang

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run tests
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          ctest --test-dir build --output-on-failure
        else
          ctest --test-dir build --output-on-failure -C ${{ matrix.build_type }}
        fi
      shell: bash